.TH CMP 1
.SH NAME
cmp \- compare two files
.SH SYNOPSIS
.B cmp
[
.BR -l | -s
]
.I file1
.I file2
.SH DESCRIPTION
The
.I cmp
utility compares two files. The
.I cmp
utility writes no output if the files are the same. Under default
options, if they differ, it writes to standard output the byte and
line number at which the first difference occurred. Bytes and lines
are numbered beginning with 1. If
.I file1
or
.I file2
is '-' , the standard input is used.
.PP
The following options are supported:
.TP
.B -l
Write the byte number (decimal) and the differing bytes (octal)
for each difference.
.TP
.B -s
Write nothing for differing files; return exit status only.
.SH SEE ALSO
comm(1), diff(1)
