.TH DIRNAME 1
.SH NAME
dirname \- return the directory portion of a pathname
.SH SYNOPSIS
.B dirname
.I string
.SH DESCRIPTION
The string
.I string
is converted to the name of the directory containing the filename
corresponding to the last pathname component in
.IR string .
.SH SEE ALSO
basename(1)
